const COURSE_DATA = {
        courseOne: {
            title:'Diploma of Building and Construction',
            courseId:'courseOne',
            description:'The Diploma of Building and Construction is designed for individuals who want to develop their skills and knowledge in the construction industry, and to progress their career in building and construction. The course covers the key principles of building and construction, including project management, planning and scheduling, procurement, cost management, contract administration, building codes and standards, and workplace health and safety.',
            learning_points: [
                'Construction technology and materials: Students learn about the latest construction technology, including emerging trends in materials, tools, and equipment. They also learn about the best practices for selecting, sourcing, and managing materials on a construction site.',
                'Building codes and standards: The course covers the national and state-specific building codes and regulations that govern construction projects. This includes topics such as building design, structural integrity, fire safety, and environmental regulations.',
                'Project management: The course teaches the fundamental principles of project management, including project planning, scheduling, budgeting, risk management, and communication. Students will learn how to manage a team, liaise with stakeholders, and effectively use project management software.',
                'Estimating and costing: Students learn how to estimate and cost a construction project, including how to calculate costs for labour, materials, equipment, and overheads. They also learn how to read and interpret construction drawings and specifications.',
                'Contract administration: The course covers the legal and contractual aspects of construction projects, including procurement, tendering, and contract management. Students learn how to negotiate and manage contracts, as well as how to identify and mitigate legal risks.',
                'Planning and scheduling: The course teaches students how to plan and schedule construction projects, including how to use Gantt charts, critical path analysis, and other project management tools. Students will also learn how to create construction schedules and timelines.',
                'Workplace health and safety: Students learn about workplace health and safety regulations, and how to identify and control hazards on a construction site. They also learn how to develop and implement workplace health and safety policies and procedures.',
                'Quality control: The course covers the principles of quality control in construction projects, including how to develop and implement quality control plans, conduct inspections, and manage quality-related issues.',
                'Environmental sustainability: The course covers environmental sustainability practices in construction projects, including how to reduce waste, conserve energy, and use sustainable materials.',
            ],
            course_content: [
                'Building codes and standards',
                'Construction technology and materials',
                'Project management',
                'Estimating and costing',
                'Contract administration',
                'Planning and scheduling',
                'Quality control',
                'Workplace health and safety',
                'Legal and regulatory compliance',
                'Sustainability and environmental management',
                'Risk management',
            ],
            course_assessment:'Assessment methods may vary depending on the institution, but typically include a combination of written assignments, projects, practical tasks, and exams. The assessment tasks are designed to ensure that students have a comprehensive understanding of the course content and can apply their knowledge and skills to real-world situations.',
            entry_requirement:[
                'A completed Year 12 or equivalent',
                'Demonstrated knowledge of the building and construction industry',
                'Relevant work experience in the industry',
                'A satisfactory result in an English language proficiency test (if English is not the students first language)',
            ],
            career_opportunity:[
                'Building supervisor',
                'Construction manager',
                'Building estimator',
                'Site supervisor',
                'Contract administrator',
            ],
            course_fee_desc:'Course fees may vary depending on the institution offering the course, but typically range from $10,000 to $25,000 AUD for the full course.',
            duration:'This course is delivered over a period of 24 weeks',
            dates:'We have intakes in March, June and November',
            location:'Zoom | Melbourne',
            instructor:'Jhon Doe',
            course_fee:6000,	
        },
        courseTwo: {
            title:'Certificate IV in Building & Construction (Building)',
            courseId:'courseTwo',
            description:'The Diploma of Building and Construction is designed for individuals who want to develop their skills and knowledge in the construction industry, and to progress their career in building and construction. The course covers the key principles of building and construction, including project management, planning and scheduling, procurement, cost management, contract administration, building codes and standards, and workplace health and safety.',
            learning_points: [
                'Construction technology and materials: Students learn about the latest construction technology, including emerging trends in materials, tools, and equipment. They also learn about the best practices for selecting, sourcing, and managing materials on a construction site.',
                'Building codes and standards: The course covers the national and state-specific building codes and regulations that govern construction projects. This includes topics such as building design, structural integrity, fire safety, and environmental regulations.',
                'Project management: The course teaches the fundamental principles of project management, including project planning, scheduling, budgeting, risk management, and communication. Students will learn how to manage a team, liaise with stakeholders, and effectively use project management software.',
                'Estimating and costing: Students learn how to estimate and cost a construction project, including how to calculate costs for labour, materials, equipment, and overheads. They also learn how to read and interpret construction drawings and specifications.',
                'Contract administration: The course covers the legal and contractual aspects of construction projects, including procurement, tendering, and contract management. Students learn how to negotiate and manage contracts, as well as how to identify and mitigate legal risks.',
                'Planning and scheduling: The course teaches students how to plan and schedule construction projects, including how to use Gantt charts, critical path analysis, and other project management tools. Students will also learn how to create construction schedules and timelines.',
                'Workplace health and safety: Students learn about workplace health and safety regulations, and how to identify and control hazards on a construction site. They also learn how to develop and implement workplace health and safety policies and procedures.',
                'Quality control: The course covers the principles of quality control in construction projects, including how to develop and implement quality control plans, conduct inspections, and manage quality-related issues.',
                'Environmental sustainability: The course covers environmental sustainability practices in construction projects, including how to reduce waste, conserve energy, and use sustainable materials.',
            ],
            course_content: [
                'Building codes and standards',
                'Construction technology and materials',
                'Project management',
                'Estimating and costing',
                'Contract administration',
                'Planning and scheduling',
                'Quality control',
                'Workplace health and safety',
                'Legal and regulatory compliance',
                'Sustainability and environmental management',
                'Risk management',
            ],
            course_assessment:'Assessment methods may vary depending on the institution, but typically include a combination of written assignments, projects, practical tasks, and exams. The assessment tasks are designed to ensure that students have a comprehensive understanding of the course content and can apply their knowledge and skills to real-world situations.',
            entry_requirement:[
                'A completed Year 12 or equivalent',
                'Demonstrated knowledge of the building and construction industry',
                'Relevant work experience in the industry',
                'A satisfactory result in an English language proficiency test (if English is not the students first language)',
            ],
            career_opportunity:[
                'Building supervisor',
                'Construction manager',
                'Building estimator',
                'Site supervisor',
                'Contract administrator',
            ],
            course_fee_desc:'Course fees may vary depending on the institution offering the course, but typically range from $10,000 to $25,000 AUD for the full course.',
            duration:'This course is delivered over a period of 24 weeks',
            dates:'We have intakes in March, June and November',
            location:'Zoom | Melbourne',
            instructor:'Jhon Doe',
            course_fee:1000,
        },
        courseThree: {
            title:'Certificate III Work Health & Safety',
            courseId:'courseThree',
            description:'The Diploma of Building and Construction is designed for individuals who want to develop their skills and knowledge in the construction industry, and to progress their career in building and construction. The course covers the key principles of building and construction, including project management, planning and scheduling, procurement, cost management, contract administration, building codes and standards, and workplace health and safety.',
            learning_points: [
                'Construction technology and materials: Students learn about the latest construction technology, including emerging trends in materials, tools, and equipment. They also learn about the best practices for selecting, sourcing, and managing materials on a construction site.',
                'Building codes and standards: The course covers the national and state-specific building codes and regulations that govern construction projects. This includes topics such as building design, structural integrity, fire safety, and environmental regulations.',
                'Project management: The course teaches the fundamental principles of project management, including project planning, scheduling, budgeting, risk management, and communication. Students will learn how to manage a team, liaise with stakeholders, and effectively use project management software.',
                'Estimating and costing: Students learn how to estimate and cost a construction project, including how to calculate costs for labour, materials, equipment, and overheads. They also learn how to read and interpret construction drawings and specifications.',
                'Contract administration: The course covers the legal and contractual aspects of construction projects, including procurement, tendering, and contract management. Students learn how to negotiate and manage contracts, as well as how to identify and mitigate legal risks.',
                'Planning and scheduling: The course teaches students how to plan and schedule construction projects, including how to use Gantt charts, critical path analysis, and other project management tools. Students will also learn how to create construction schedules and timelines.',
                'Workplace health and safety: Students learn about workplace health and safety regulations, and how to identify and control hazards on a construction site. They also learn how to develop and implement workplace health and safety policies and procedures.',
                'Quality control: The course covers the principles of quality control in construction projects, including how to develop and implement quality control plans, conduct inspections, and manage quality-related issues.',
                'Environmental sustainability: The course covers environmental sustainability practices in construction projects, including how to reduce waste, conserve energy, and use sustainable materials.',
            ],
            course_content: [
                'Building codes and standards',
                'Construction technology and materials',
                'Project management',
                'Estimating and costing',
                'Contract administration',
                'Planning and scheduling',
                'Quality control',
                'Workplace health and safety',
                'Legal and regulatory compliance',
                'Sustainability and environmental management',
                'Risk management',
            ],
            course_assessment:'Assessment methods may vary depending on the institution, but typically include a combination of written assignments, projects, practical tasks, and exams. The assessment tasks are designed to ensure that students have a comprehensive understanding of the course content and can apply their knowledge and skills to real-world situations.',
            entry_requirement:[
                'A completed Year 12 or equivalent',
                'Demonstrated knowledge of the building and construction industry',
                'Relevant work experience in the industry',
                'A satisfactory result in an English language proficiency test (if English is not the students first language)',
            ],
            career_opportunity:[
                'Building supervisor',
                'Construction manager',
                'Building estimator',
                'Site supervisor',
                'Contract administrator',
            ],
            course_fee_desc:'Course fees may vary depending on the institution offering the course, but typically range from $10,000 to $25,000 AUD for the full course.',
            duration:'This course is delivered over a period of 24 weeks',
            dates:'We have intakes in March, June and November',
            location:'Zoom | Melbourne',
            instructor:'Jhon Doe',
            course_fee:4000,
        },
        courseFour: {
            title:'Builder Registration Program (Domestic & Commercial)',
            courseId:'courseFour',
            description:'The Diploma of Building and Construction is designed for individuals who want to develop their skills and knowledge in the construction industry, and to progress their career in building and construction. The course covers the key principles of building and construction, including project management, planning and scheduling, procurement, cost management, contract administration, building codes and standards, and workplace health and safety.',
            learning_points: [
                'Construction technology and materials: Students learn about the latest construction technology, including emerging trends in materials, tools, and equipment. They also learn about the best practices for selecting, sourcing, and managing materials on a construction site.',
                'Building codes and standards: The course covers the national and state-specific building codes and regulations that govern construction projects. This includes topics such as building design, structural integrity, fire safety, and environmental regulations.',
                'Project management: The course teaches the fundamental principles of project management, including project planning, scheduling, budgeting, risk management, and communication. Students will learn how to manage a team, liaise with stakeholders, and effectively use project management software.',
                'Estimating and costing: Students learn how to estimate and cost a construction project, including how to calculate costs for labour, materials, equipment, and overheads. They also learn how to read and interpret construction drawings and specifications.',
                'Contract administration: The course covers the legal and contractual aspects of construction projects, including procurement, tendering, and contract management. Students learn how to negotiate and manage contracts, as well as how to identify and mitigate legal risks.',
                'Planning and scheduling: The course teaches students how to plan and schedule construction projects, including how to use Gantt charts, critical path analysis, and other project management tools. Students will also learn how to create construction schedules and timelines.',
                'Workplace health and safety: Students learn about workplace health and safety regulations, and how to identify and control hazards on a construction site. They also learn how to develop and implement workplace health and safety policies and procedures.',
                'Quality control: The course covers the principles of quality control in construction projects, including how to develop and implement quality control plans, conduct inspections, and manage quality-related issues.',
                'Environmental sustainability: The course covers environmental sustainability practices in construction projects, including how to reduce waste, conserve energy, and use sustainable materials.',
            ],
            course_content: [
                'Building codes and standards',
                'Construction technology and materials',
                'Project management',
                'Estimating and costing',
                'Contract administration',
                'Planning and scheduling',
                'Quality control',
                'Workplace health and safety',
                'Legal and regulatory compliance',
                'Sustainability and environmental management',
                'Risk management',
            ],
            course_assessment:'Assessment methods may vary depending on the institution, but typically include a combination of written assignments, projects, practical tasks, and exams. The assessment tasks are designed to ensure that students have a comprehensive understanding of the course content and can apply their knowledge and skills to real-world situations.',
            entry_requirement:[
                'A completed Year 12 or equivalent',
                'Demonstrated knowledge of the building and construction industry',
                'Relevant work experience in the industry',
                'A satisfactory result in an English language proficiency test (if English is not the students first language)',
            ],
            career_opportunity:[
                'Building supervisor',
                'Construction manager',
                'Building estimator',
                'Site supervisor',
                'Contract administrator',
            ],
            course_fee_desc:'Course fees may vary depending on the institution offering the course, but typically range from $10,000 to $25,000 AUD for the full course.',
            duration:'This course is delivered over a period of 24 weeks',
            dates:'We have intakes in March, June and November',
            location:'Zoom | Melbourne',
            instructor:'Jane Doe',
            course_fee:10000,
        },
        courseFive: {
            title:'Building Permit Applications',
            courseId:'courseFive',
            description:'The Diploma of Building and Construction is designed for individuals who want to develop their skills and knowledge in the construction industry, and to progress their career in building and construction. The course covers the key principles of building and construction, including project management, planning and scheduling, procurement, cost management, contract administration, building codes and standards, and workplace health and safety.',
            learning_points: [
                'Construction technology and materials: Students learn about the latest construction technology, including emerging trends in materials, tools, and equipment. They also learn about the best practices for selecting, sourcing, and managing materials on a construction site.',
                'Building codes and standards: The course covers the national and state-specific building codes and regulations that govern construction projects. This includes topics such as building design, structural integrity, fire safety, and environmental regulations.',
                'Project management: The course teaches the fundamental principles of project management, including project planning, scheduling, budgeting, risk management, and communication. Students will learn how to manage a team, liaise with stakeholders, and effectively use project management software.',
                'Estimating and costing: Students learn how to estimate and cost a construction project, including how to calculate costs for labour, materials, equipment, and overheads. They also learn how to read and interpret construction drawings and specifications.',
                'Contract administration: The course covers the legal and contractual aspects of construction projects, including procurement, tendering, and contract management. Students learn how to negotiate and manage contracts, as well as how to identify and mitigate legal risks.',
                'Planning and scheduling: The course teaches students how to plan and schedule construction projects, including how to use Gantt charts, critical path analysis, and other project management tools. Students will also learn how to create construction schedules and timelines.',
                'Workplace health and safety: Students learn about workplace health and safety regulations, and how to identify and control hazards on a construction site. They also learn how to develop and implement workplace health and safety policies and procedures.',
                'Quality control: The course covers the principles of quality control in construction projects, including how to develop and implement quality control plans, conduct inspections, and manage quality-related issues.',
                'Environmental sustainability: The course covers environmental sustainability practices in construction projects, including how to reduce waste, conserve energy, and use sustainable materials.',
            ],
            course_content: [
                'Building codes and standards',
                'Construction technology and materials',
                'Project management',
                'Estimating and costing',
                'Contract administration',
                'Planning and scheduling',
                'Quality control',
                'Workplace health and safety',
                'Legal and regulatory compliance',
                'Sustainability and environmental management',
                'Risk management',
            ],
            course_assessment:'Assessment methods may vary depending on the institution, but typically include a combination of written assignments, projects, practical tasks, and exams. The assessment tasks are designed to ensure that students have a comprehensive understanding of the course content and can apply their knowledge and skills to real-world situations.',
            entry_requirement:[
                'A completed Year 12 or equivalent',
                'Demonstrated knowledge of the building and construction industry',
                'Relevant work experience in the industry',
                'A satisfactory result in an English language proficiency test (if English is not the students first language)',
            ],
            career_opportunity:[
                'Building supervisor',
                'Construction manager',
                'Building estimator',
                'Site supervisor',
                'Contract administrator',
            ],
            course_fee_desc:'Course fees may vary depending on the institution offering the course, but typically range from $10,000 to $25,000 AUD for the full course.',
            duration:'This course is delivered over a period of 24 weeks',
            dates:'We have intakes in March, June and November',
            location:'Zoom | Melbourne',
            instructor:'Jhon Doe Mark',
            course_fee:15000,
        },
        courseSix: {
            title:'Free – Infection Control (Building & Construction)',
            courseId:'courseSix',
            description:'The Diploma of Building and Construction is designed for individuals who want to develop their skills and knowledge in the construction industry, and to progress their career in building and construction. The course covers the key principles of building and construction, including project management, planning and scheduling, procurement, cost management, contract administration, building codes and standards, and workplace health and safety.',
            learning_points: [
                'Construction technology and materials: Students learn about the latest construction technology, including emerging trends in materials, tools, and equipment. They also learn about the best practices for selecting, sourcing, and managing materials on a construction site.',
                'Building codes and standards: The course covers the national and state-specific building codes and regulations that govern construction projects. This includes topics such as building design, structural integrity, fire safety, and environmental regulations.',
                'Project management: The course teaches the fundamental principles of project management, including project planning, scheduling, budgeting, risk management, and communication. Students will learn how to manage a team, liaise with stakeholders, and effectively use project management software.',
                'Estimating and costing: Students learn how to estimate and cost a construction project, including how to calculate costs for labour, materials, equipment, and overheads. They also learn how to read and interpret construction drawings and specifications.',
                'Contract administration: The course covers the legal and contractual aspects of construction projects, including procurement, tendering, and contract management. Students learn how to negotiate and manage contracts, as well as how to identify and mitigate legal risks.',
                'Planning and scheduling: The course teaches students how to plan and schedule construction projects, including how to use Gantt charts, critical path analysis, and other project management tools. Students will also learn how to create construction schedules and timelines.',
                'Workplace health and safety: Students learn about workplace health and safety regulations, and how to identify and control hazards on a construction site. They also learn how to develop and implement workplace health and safety policies and procedures.',
                'Quality control: The course covers the principles of quality control in construction projects, including how to develop and implement quality control plans, conduct inspections, and manage quality-related issues.',
                'Environmental sustainability: The course covers environmental sustainability practices in construction projects, including how to reduce waste, conserve energy, and use sustainable materials.',
            ],
            course_content: [
                'Building codes and standards',
                'Construction technology and materials',
                'Project management',
                'Estimating and costing',
                'Contract administration',
                'Planning and scheduling',
                'Quality control',
                'Workplace health and safety',
                'Legal and regulatory compliance',
                'Sustainability and environmental management',
                'Risk management',
            ],
            course_assessment:'Assessment methods may vary depending on the institution, but typically include a combination of written assignments, projects, practical tasks, and exams. The assessment tasks are designed to ensure that students have a comprehensive understanding of the course content and can apply their knowledge and skills to real-world situations.',
            entry_requirement:[
                'A completed Year 12 or equivalent',
                'Demonstrated knowledge of the building and construction industry',
                'Relevant work experience in the industry',
                'A satisfactory result in an English language proficiency test (if English is not the students first language)',
            ],
            career_opportunity:[
                'Building supervisor',
                'Construction manager',
                'Building estimator',
                'Site supervisor',
                'Contract administrator',
            ],
            course_fee_desc:'Course fees may vary depending on the institution offering the course, but typically range from $10,000 to $25,000 AUD for the full course.',
            duration:'This course is delivered over a period of 24 weeks',
            dates:'We have intakes in March, June and November',
            location:'Zoom | Melbourne',
            instructor:'Jhon Doe',
            course_fee:20000,
        }
    }

export default COURSE_DATA